### ISSUE TITLE
About "--"

### ISSUE THREAD

**Issue by ghost** [SivilTaram/BUAAOS-guide-book#10]
Maybe Helpful:
![--](https://cloud.githubusercontent.com/assets/22797176/23821432/f6cd4b80-066c-11e7-97d7-f0648442afa3.JPG)

**Comment by ghost** [comment]
我不知道Issue不能删就直接发出来了。。。其实应该合并到那个bug下面的。。。

**Comment by sighingnow** [comment]
Seems duplicate with #3.
