### ISSUE TITLE
Errta of Chapter 2

### ISSUE THREAD

**Issue by LeoJacob** [SivilTaram/BUAAOS-guide-book#11]
NEW:
P50, 第一段末，"PADDR 和KADDR 两个宏来实验..." 应为 “实现”。

ADVICE:
P56, 2.9，挑战性任务是否应注明实现 buddy system?

SOLVED:
P46, 2.3 第一行 “4GB(2^32)” 显示不对。
P46, 2.3 地址中 "ff" 的连写问题。（general）
P46, 2.3 地址布局中 kseg1 中 “与 kseg1 类似，这段地址也是内核地址” 应该为 “与 kseg0 类似....”。
P46, 2.4 第一行 “是尾每个程序” 应为 “是为...”。
P47, 2.5.1 第一行 “第一实验” 应为 “第一个实验”。
P50, 最后一行 “以凭借索引“ 应删除 ”以“ 或者 ”凭借“。
P52, "0x7fc00000 » 12"，右移符号的显示问题。（general）

**Comment by sighingnow** [comment]
cc @liukangxu

**Comment by SivilTaram** [comment]
Thanks for your advice, nice work!

**Comment by liukangxu** [comment]
All fixed except the last suggestion, maybe open a new issue? @LeoJacob
