### ISSUE TITLE
关闭对 untaged commit 的自动 release

### ISSUE THREAD

**Issue by liukangxu** [SivilTaram/BUAAOS-guide-book#14]
如题~

@mycraftmw

**Comment by sighingnow** [comment]
In our current setting, a built pdf file will be deployed as a release every time when travis-ci successfully builds our guide book. Our original motivation of this setting was that it may be more helpful for students to access our newest version of pdf book without set up the whole LaTeX environment locally. Our changesets could be delivered more timely by this way. I'm in favor of our current setting that upload pdf after every successful build, although these untaged releases may raise some noises.

**Comment by SivilTaram** [comment]
I think direct commit to master without implementing the whole feature is not good enough. The better strategy is that you create `dev` branch to develop, or just use pull request. We can just use `master` branch to release, do you think so?

**Comment by SivilTaram** [comment]
I have seen the code which could have avoided building commit without tags in `.travis.yml`.
```
branches:
  only:
    - /^v[\d.]+\d$/
    - master
```
If you want to implement the requirements, you can remove the line `- master`. :)

**Comment by SivilTaram** [comment]
Tongyu has fixed it. :)

**Comment by mycraftmw** [comment]
I think we should build every commit in the master branch to make sure it can be built correctly every time.And we just deploy those who has been tagged to avoid some unimportant commits to be deployed.
So I just add `tags: true` in `deploy: on:`。
