### ISSUE TITLE
Exercise 3.1 语言表述不清且似乎与给出代码有所冲突

### ISSUE THREAD

**Issue by Jueast** [SivilTaram/BUAAOS-guide-book#2]
> 我们需要在mips_detect_memory() 函数中这几个全局变量

这句话感觉看不明

然后似乎mm/pmap.c 中 `mips_detect_memory()` 已经实现了？

没有找到相应的注释。。

**Comment by SivilTaram** [comment]
这是服务端代码的问题...我已经告知学长更换一个新的lab2分支了...现在放的还是以前的代码
