### ISSUE TITLE
git命令

### ISSUE THREAD

**Issue by SivilTaram** [SivilTaram/BUAAOS-guide-book#3]
Latex环境下`git rm --cached`类似的语法在加粗时会只显示为 `-` 一个横杠。

**Comment by sighingnow** [comment]
这个是Tex-Ligature的问题。有个microtype宏包可以全局替换，但是对xelatex的支持不好，我试了下没效果。要不把这类shell命令都放在`\mintinline`环境里如何？

**Comment by liukangxu** [comment]
closed by commit 663ba78
